# Generated by Django 3.1.6 on 2021-02-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mukja', '0006_golmok_head_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golmok',
            old_name='head_image',
            new_name='head_image1',
        ),
        migrations.AddField(
            model_name='golmok',
            name='head_image2',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
