# Generated by Django 3.1.5 on 2021-02-16 14:45

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mukja', '0009_remove_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=markdownx.models.MarkdownxField(null=True),
        ),
    ]
