# Generated by Django 3.1.5 on 2021-02-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mukja', '0012_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='subtitle',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='text',
            field=models.TextField(max_length=25),
        ),
    ]
